// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: menu.sql

package db

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, restaurant_id, status, order_details)
VALUES ($1, $2, $3, $4)
RETURNING order_id, customer_id, restaurant_id, status, order_details, created_at
`

type CreateOrderParams struct {
	CustomerID   int32
	RestaurantID int32
	Status       string
	OrderDetails []byte
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerID,
		arg.RestaurantID,
		arg.Status,
		arg.OrderDetails,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.CustomerID,
		&i.RestaurantID,
		&i.Status,
		&i.OrderDetails,
		&i.CreatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT order_id, customer_id, restaurant_id, status, order_details, created_at
FROM orders
WHERE order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID int32) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.CustomerID,
		&i.RestaurantID,
		&i.Status,
		&i.OrderDetails,
		&i.CreatedAt,
	)
	return i, err
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT order_id, customer_id, restaurant_id, status, order_details, created_at
FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID int32) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.OrderID,
			&i.CustomerID,
			&i.RestaurantID,
			&i.Status,
			&i.OrderDetails,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1
WHERE order_id = $2
`

type UpdateOrderStatusParams struct {
	Status  string
	OrderID int32
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, arg.Status, arg.OrderID)
	return err
}
