// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: resturant.sql

package db

import (
	"context"
)

const createRestaurant = `-- name: CreateRestaurant :one
INSERT INTO restaurants (
    name,
    address,
    phone_number,
    owner_id
) VALUES (
    $1, $2, $3, $4
) RETURNING restaurant_id, name, address, phone_number, owner_id
`

type CreateRestaurantParams struct {
	Name        string
	Address     string
	PhoneNumber string
	OwnerID     int32
}

func (q *Queries) CreateRestaurant(ctx context.Context, arg CreateRestaurantParams) (Restaurant, error) {
	row := q.db.QueryRow(ctx, createRestaurant,
		arg.Name,
		arg.Address,
		arg.PhoneNumber,
		arg.OwnerID,
	)
	var i Restaurant
	err := row.Scan(
		&i.RestaurantID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.OwnerID,
	)
	return i, err
}

const getRestaurantName = `-- name: GetRestaurantName :one
SELECT name FROM restaurants WHERE restaurant_id = $1
`

func (q *Queries) GetRestaurantName(ctx context.Context, restaurantID int32) (string, error) {
	row := q.db.QueryRow(ctx, getRestaurantName, restaurantID)
	var name string
	err := row.Scan(&name)
	return name, err
}
